@Id = 0

### Get all todos
GET http://localhost:5082/todo

### Get todo by Id
# @prompt todoId
# @name getTodo
GET http://localhost:5082/todo/{{todoId}}

Id = {{getTodo.request.body.id}}

### Add todo
POST http://localhost:5082/todo
Content-Type: application/json

{
    "title": "Todo N° {{$randomInt 1 1000}}"
}

### Update todo
PUT http://localhost:5082/todo/{{Id}}
Content-Type: application/json

{
    "title": "Todo N° two"
}

### Delete todo
DELETE  http://localhost:5082/todo/{{Id}}
Content-Type: application/json

{
    "title": "Todo N° two"
}

### Complete todo
PUT http://localhost:5082/todo/{{Id}}/complete
Content-Type: application/json

### Start todo
PUT http://localhost:5082/todo/{{Id}}/start
Content-Type: application/json